;;;; sendfile.import.scm - GENERATED BY CHICKEN 4.6.3 -*- Scheme -*-

(eval '(import chicken scheme extras posix srfi-4 foreign lolevel))
(##sys#register-compiled-module
  'sendfile
  (list)
  '((force-implementation . sendfile#force-implementation)
    (*last-selected-implementation* . sendfile#*last-selected-implementation*)
    (read-write-buffer-size . sendfile#read-write-buffer-size)
    (implementation-selector . sendfile#implementation-selector)
    (impl:mmapped . sendfile#impl:mmapped)
    (impl:sendfile . sendfile#impl:sendfile)
    (impl:read-write-loop/fd . sendfile#impl:read-write-loop/fd)
    (impl:read-write-loop/port . sendfile#impl:read-write-loop/port)
    (mmap-available . sendfile#mmap-available)
    (sendfile-available . sendfile#sendfile-available)
    (sendfile . sendfile#sendfile))
  (list)
  (list))

;; END OF FILE
